export const GET_PRODUCTS_START = 'GET_PRODUCTS_START';
export const GET_PRODUCTS_SUCCESS = 'GET_PRODUCTS_SUCCESS';
export const GET_PRODUCTS_FAILURE = 'GET_PRODUCTS_FAILURE';

export const GET_CATEGORIES_START = 'GET_CATEGORIES_START';
export const GET_CATEGORIES_SUCCESS = 'GET_CATEGORIES_SUCCESS';
export const GET_CATEGORIES_FAILURE = 'GET_CATEGORIES_FAILURE';

export const GET_PRODUCT_BY_ID_START = 'GET_PRODUCT_BY_ID_START';
export const GET_PRODUCT_BY_ID_SUCCESS = 'GET_PRODUCT_BY_ID_SUCCESS';
export const GET_PRODUCT_BY_ID_FAILURE = 'GET_PRODUCT_BY_ID_FAILURE';

export const ADD_PRODUCT_TO_CART = 'ADD_PRODUCT_TO_CART';

export const SEARCH_PRODUCT = 'SEARCH_PRODUCT';

export const ADD_ONE_PRODUCT_TO_CART = 'ADD_ONE_PRODUCT_TO_CART';

export const REMOVE_PRODUCT_FROM_CART = 'REMOVE_PRODUCT_FROM_CART';

export const CLEAN_CART = 'CLEAN_CART';